### ISSUE TITLE
Cryptic error messages

### ISSUE THREAD

**Issue by sirikid** [doublep/eldev#14]
**Error message:**
```No .el files with package headers in ‘/.../’```

But checkdoc passes just fine, the cause was the version field. I've added all the required keywords from the info, if eldev requires more than that, it would be useful to have better error messages and/or a separate checker.

**Comment by doublep** [comment]
I agree the message is bad, but I have no idea how you got it. Please provide at least the command that you used (`$ eldev foo ...`) and ideally also the package, e.g. GitHub URL if it is public.

**Comment by sirikid** [comment]
[Repo](https://git.sr.ht/~sokolov/eldev-cryptic-errors), [build](https://builds.sr.ht/~sokolov/job/242824)

**Comment by doublep** [comment]
This message comes from Emacs itself, so I cannot really change it. However, Eldev now adds some hints to it, hopefully making it less confusing.

**Comment by sirikid** [comment]
Thanks!
