### ISSUE TITLE
Install specific version of package / upgrade built-in package / deal with org-mode

### ISSUE THREAD

**Issue by Trevoke** [doublep/eldev#18]
Hi folks,

I'm working on a package that requires a more recent version of org-mode than ships with most versions of emacs (the build passes with 27.1). So I need to ask eldev to install a more recent version of org-mode. How do I do this with eldev?

**Comment by Trevoke** [comment]
`eldev prepare` fixed it, thanks! It might be worth calling this out explicitly in the readme?

**Comment by doublep** [comment]
Fix released as part of 0.7.
