### ISSUE TITLE
lint package does not load local dependencies

### ISSUE THREAD

**Issue by taku0** [doublep/eldev#19]
`lint package` command does not load local dependencies.  It results in `error: Package foo is not installable`.

## Sample project

[sample.zip](https://github.com/doublep/eldev/files/5146758/sample.zip)

The sample project has two packages: `sub` and `main`. `main` depends on `sub`.

## Steps to reproduce

1. unzip the sample project.
2. `cd sample/main`
3. `eldev lint package main.el`

## Expected result

No errors.

## Actual result

```
$ eldev lint package main.el
main.el:4:38: error: Package sub is not installable.
Found 1 warning in file ‘main.el’
Linting produced warnings
```

## Note

`eldev test` works fine without errors. It loads the `sub` and call it successfully.

**Comment by doublep** [comment]
Thank you for the detailed report. Will be fixed in 0.7.1 that I will release later today.
