### ISSUE TITLE
Support for checkdoc

### ISSUE THREAD

**Issue by DamienCassou** [doublep/eldev#2]
Checkdoc is a package provided with Emacs core that checks Emacs lisp docstrings. It is useful to make sure that each docstring correctly references every parameter for example.

It would be great to add support for checkdoc in eldev. [makem.sh](https://github.com/alphapapa/makem.sh/blob/master/makem.sh) has support for checkdoc already so you can have a look if you want.

**Comment by doublep** [comment]
Would it be enough to add command `lint` that runs all currently supported linters on your package? Of course with a way to select particular linter, etc. Or do you envision integration into existing commands, e.g. `test` somehow?

**Comment by DamienCassou** [comment]
> Would it be enough to add command lint that runs all currently supported linters on your package? Of course with a way to select particular linter, etc.

this would do just fine I think

> Or do you envision integration into existing commands, e.g. test somehow?

I think `test` and `lint` should be kept separate. One checks the quality of behavior and the other the quality of code.

**Comment by doublep** [comment]
I committed new `lint` command that supports `checkdoc`, `package-lint` and `relint` (`indent-lint` is not easy, maybe will add later). Can you provide some feedback? It's not yet documented, but `eldev help lint` should give enough information. 

The easiest way to test is by using the fourth installation method from https://github.com/doublep/eldev#installation. You don't need to set `ELDEV_LOCAL` permanently, e.g. this should suffice:

    $ ELDEV_LOCAL=~/git/eldev eldev lint

No special preparations are needed, Eldev will download necessary packages when it needs to (for this reason, first linting will be slow).

**Comment by doublep** [comment]
Done in 0.2.

**Comment by alphapapa** [comment]
@doublep Regarding linting indentation, you may find this helpful: https://github.com/alphapapa/makem.sh/commit/3c5165d5aa43ee386f9b1dfbe44156ae0f060828
