### ISSUE TITLE
external packages not honored?

### ISSUE THREAD

**Issue by Apteryks** [doublep/eldev#28]
Hello,

On my system, I make use of what `package.el` calls 'external packages', via a custom entry added to the `package-directory-list` variable. Unfortunately, it seems that eldev is ignoring those, and when I run "eldev test" on a project, it complains that these dependencies are not available.  Here's an example while attempting to run the test suite of the logview package:

```
$ eldev test
Dependency ‘datetime’ 0.6.1 is not available                                                             |
Required by package ‘logview’
```

M-x package-list does show datetime at the right version: ` datetime           0.6.1         external   No description available.`

In a related note, packages directly added to the load path, via EMACSLOADPATH for example, are also ignored.

I haven't looked into eldev's internals, but I feel packages made available this way should be honored by eldev.

**Comment by doublep** [comment]
Eldev is intentionally isolated from your normal Emacs as much as possible. It installs and manages all dependencies on its own, regardless of how (and even if) they are available in your Emacs. See [Project dependencies](https://github.com/doublep/eldev#project-dependencies) section in the documentation.

For 0.8 an option to use installed Emacs packages is planned, but still it will be an option, not a change in the behavior.

**Comment by Apteryks** [comment]
OK. Yes such option would be very welcome, e.g. for packaging Emacs packages at the system level (for use with a general purpose package manager such as Guix).

**Comment by doublep** [comment]
Done in commit 344863e: Add a global option to partially disable project isolation and use preinstalled dependencies, e.g. from `~/.emacs.d/elpa'.

Documentation is in the usual place.
