### ISSUE TITLE
Support package-lint

### ISSUE THREAD

**Issue by DamienCassou** [doublep/eldev#3]
[package-lint](https://github.com/purcell/package-lint) is a package that checks package related meta-data in an Emacs lisp file and a bunch of other package-related properties. It is useful to make sure that an Emacs lisp package plays nicely with the others.

It would be great to add support for package-lint in eldev. [makem.sh](https://github.com/alphapapa/makem.sh/blob/master/makem.sh) has support for package-lint already so you can have a look if you want.

**Comment by doublep** [comment]
Done in 0.2.
