### ISSUE TITLE
Recent undercover changes seem to require changes in Eldev

### ISSUE THREAD

**Issue by DarwinAwardWinner** [doublep/eldev#30]
As noted in [this issue comment](https://github.com/undercover-el/undercover.el/issues/54#issuecomment-766183467), recent changes to the internals of undercover.el appear to have invalidated some assumptions of Eldev in a way that makes undercover unusable from Eldev. Attempting to do so causes an error.

(Note that the linked issue is about an unrelated issue in undercover. While attempting to test a fix for that issue, I ran into this issue.)

**Comment by doublep** [comment]
I fixed this half an hour ago in commit fb72721, as I saw the ping. Still goes into internals, but `undercover` currently gives no other option. Hopefully this will change at some point.
