### ISSUE TITLE
Support for ecuks

### ISSUE THREAD

**Issue by twlz0ne** [doublep/eldev#33]
[Ecukes](https://github.com/ecukes/ecukes) is Cucumber for Emacs.

Seems it can be easily intergrated with cask: [ecukes#installation](https://github.com/ecukes/ecukes#installation)

> ## Installation
> 
> Add `ecukes` to your [Cask](https://github.com/rejeep/cask.el) file:
> 
> ```lisp
> (source melpa)
> 
> (package "super-duper" "0.0.1" "Super Duper.")
> 
> (development
>  (depends-on "ecukes"))
> ```
> 
> Then run `cask` to install.
> 
> Create an Elisp file in the root directory called `super-duper.el` and
> `(provide 'super-duper)`. To setup Ecukes for the project, run:
> 
> ```
> $ cask exec ecukes new
> 
> create features
> create   step-definition
> create     super-duper-steps.el
> create   support
> create     env.el
> create   super-duper.feature
> ```

Packages are using ecukes:

- https://github.com/emacs-lsp/lsp-mode
- https://github.com/7696122/evil-terminal-cursor-changer
- https://github.com/rejeep/commander.el
- https://github.com/jwiegley/emacs-chess
- More https://github.com/search?q=ecukes+filename%3ACask+language%3A%22Emacs+Lisp%22&type=Code

**Comment by doublep** [comment]
The largest problem appears to be that it doesn't like batch mode, so has to be run in a separate Emacs subprocess. Also, it is overall very unlike the currently supported frameworks and doesn't use `.el` files to declare tests.

**Comment by doublep** [comment]
Since 0.10 Eldev supports default (script/batch) mode of Ecukes. Support for win/no-win mode might be added later, but it's not easy.
