### ISSUE TITLE
Teach package-lint that there is a multi-file package when linting

### ISSUE THREAD

**Issue by publicimageltd** [doublep/eldev#54]
If I run `eldev lint` on a multi-file package, the linter complains about missing dependency declarations for each file even though I have a metadata file (`foo-pkg.el`). Looking at the repo of `package-lint`, it seems that is an often discussed issue. While `package-lint` works well with single files, there seems to be no easy way to handle multi-file packages. I don't quite understand the problems, but fact is that multi file support is not yet there. However, some build systems like `keg` seem to have configured it correctly. Here's the link to the discussion: https://github.com/purcell/package-lint/pull/218#issuecomment-910347206

Since I have no understanding of the underlying issues, I don't know what I am exactly demanding. But would it be possible to somehow teach Eldev that it should lint the non-core files in a multi-file package with some dependencies etc. already set (e.g., taken from the core file or from the metadata file)? Close that issue if that's not possible or too outlandish in your opinion.

**Comment by doublep** [comment]
Released in 0.10.
