### ISSUE TITLE
Eldev-format-message should accept nil values

### ISSUE THREAD

**Issue by publicimageltd** [doublep/eldev#57]
I had a test failing because `Eldev` raised a wrong type argument error. I found out that it is due to wrapping the code in question in a call to `with-temp-message`. This macro calls `(message nil)` if there had been no previous message to restore after executing body. `(message nil)` then  produces a nil value (not a string value) which in turn is not accepted by `eldev-format-message`.

To reproduce, simply execute: `eldev exec '(eldev-format-message nil)`, which raises a wrong type argument error. It should also accept a nil value.

**Comment by doublep** [comment]
I think it is fine for `eldev-format-message` to fail on nil, because e.g. `format` and `format-message` also fail. But the advises for `message` must not fail, of course. Will be fixed in 0.10. I also added a test for this.

**Comment by publicimageltd** [comment]
Ah okay, so it's the advise which is causing the error. Thanks a lot!

**Comment by doublep** [comment]
Fixed in 0.10. Thank you for reporting.
