### ISSUE TITLE
How to add extra files to a package

### ISSUE THREAD

**Issue by ikappaki** [doublep/eldev#65]
Hi,

what is the suggested way to add non-elisp files to the built package? I've been looking at the Eldev documentation for a way, and have also tried experimenting with the `:package` virtual target but to no avail. Looking at the code didn't help me either.

`eldev`'s own `Eldev` file though does seem to achieve so by use of the `eldev-file-to-package` variable. If this is the established way, could it be mentioned in the documentation please? I only discovered it by chance, while trying to formulate the question.

Thanks

**Comment by doublep** [comment]
Yes, this is the established and official way. I have now documented the variable in [section "Building packages"](https://github.com/doublep/eldev#building-packages). Thank you for the hint.

**Comment by doublep** [comment]
Note that with 1.2 the recommended way has changed a bit, although it still involves the same variable. See [the same documentation section](https://github.com/doublep/eldev#packaging) for description.
