### ISSUE TITLE
Setting custom variables inside a function that is being tested

### ISSUE THREAD

**Issue by ZelenyeShtany** [doublep/eldev#77]
Hello.

I have a function in which I call `org-export-to-file` function. Right
before that call, I set some custom variables (that affect export
results) from `ox-icalendar` package, and then set them back to
initial values after the call. Everything works fine in a usual Emacs
session, but when I run a test for the function, Emacs complains that
those custom variables are void variables, and `org-export-to-file`
function uses default values for these custom vars.

Is there something I can do about it?

**Comment by doublep** [comment]
Probably yes, but I need the project to see this myself, doesn't strike me as some problem that I immediately recognize.

**Comment by ZelenyeShtany** [comment]
I'm sorry, it happened because in my usual Emacs configuration I use orgmode on master branch,  but Eldev was using builtin orgmode version. 

Obviously, this is not an issue with Eldev.

**Comment by doublep** [comment]
Yes, see the [section on project isolation](https://github.com/doublep/eldev#project-isolation). You can probably set some variables in file `Eldev`, always or in response to some hook, or in `with-eval-after-load`.
