### ISSUE TITLE
Can I run "eldev emacs" with test deps in load-path?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [doublep/eldev#8]
I'm trying to debug an issue in my tests, and as part of that, I need to run emacs with all my test dependencies in `load-path`. However, it seems that `eldev emacs` only puts the package's own dependencies on the load path, which means that something declared as `(eldev-add-extra-dependencies 'test PKG)` won't be loadable within that emacs. Is there a way around this?

**Comment by doublep** [comment]
You can e.g.

    (eldev-add-extra-dependencies 'emacs PKG) 

or even

    (eldev-add-extra-dependencies '(test emacs) PKG)
