### ISSUE TITLE
Support for more testing frameworks?

### ISSUE THREAD

**Issue by Trevoke** [doublep/eldev#82]
Hi, how hard would it be to add support for https://github.com/rocky/emacs-test-simple ?

**Comment by doublep** [comment]
Probably not very hard, but this kinda looks abandoned with only a few commits after 2017. Do you really prefer this over Buttercup and ERT? Do you have a real active project using this framework?

**Comment by Trevoke** [comment]
"Abandoned" is relative; maybe it simply doesn't need more work.

I don't have a real active project using this framework - I like eldev and
it's convenient for CI when I do work on my packages, so I didn't actually
do a transition to this framework because I'm reaching out to you for it.

My problem with ecukes and buttercup is that they're macro-based and that
means I'm extremely dependent on that codebase working as intended without
edge cases, and have to dive into source code when documentation is
lacking, and I've had to open a few issues on buttercup to figure out the
actual behavior of the test framework -- and test frameworks shouldn't make
me doubt how they work.

As far as ERT, it's not convenient for CI, so it's not a good choice for me
(I transitioned from ERT to buttercup a while back).

Anyway, beyond all of my hangups, I think it would be really good if eldev
supported a very minimalistic test framework (e.g. from a Ruby lang
perspective, if that's an ecosystem you know, it's nice to support rspec,
but we should really support minitest, too).

**Comment by doublep** [comment]
> "Abandoned" is relative; maybe it simply doesn't need more work.

Yeah, suppose you are right.

> I don't have a real active project using this framework [...] Anyway, beyond all of my hangups, I think it would be really good if eldev supported a very minimalistic test framework

Let's put it like this: are *you* going to use it (supposing Eldev grows support for it) or not?

**Comment by Trevoke** [comment]
Hello! Sorry about dropping this for a month. 
It looks like the issue I had with my test suite has gone away. Whether it was me, eldev, buttercup, or anything else, I have no idea, but ... Now it works, so I don't *need* the other test suite right now.

I don't know if you've seen the error messages when buttercup fails but it's a massive macro salad and it's a PITA to parse or even handle, and that's not a fun user experience for writing tests, but either way. For now.. This matter is pragmatically closed. Thank you for taking the time to engage with me :)

**Comment by doublep** [comment]
> I don't know if you've seen the error messages when buttercup fails but it's a massive macro salad and it's a PITA to parse or even handle

I'd say that's a general program with Elisp backtraces. They are simply awful.

**Comment by Trevoke** [comment]
Ah then it's my inexperience with macro backtraces then,I imagined they
could be cleaned up but I suppose not :)
