### ISSUE TITLE
My Github CI actions started failing, so I'm working my way up the tree of my ignorance, starting with eldev

### ISSUE THREAD

**Issue by Trevoke** [doublep/eldev#84]
Hello!
My CI actions on Github started failing earlier this year and I can't figure out why. The action file is here:
https://github.com/Trevoke/org-gtd.el/blob/master/.github/workflows/test.yml

A sample failure is here https://github.com/Trevoke/org-gtd.el/actions/runs/4145028703/jobs/7168845293

The error, I _think_ is this:

```
2023-02-10T14:56:57.6694492Z [00:10.756]  Debugger entered--Lisp error: (error "Package does not untar cleanly into directory org-gtd-2.2.0/")
2023-02-10T14:56:57.6695947Z                signal(error ("Package does not untar cleanly into directory org-gtd-2.2.0/"))
2023-02-10T14:56:57.6696918Z                error("Package does not untar cleanly into directory %s/" "org-gtd-2.2.0")
```

I hate to trouble you with this because this probably isn't a problem with eldev (after all, it's my package...)  but I genuinely don't know what I could have done to cause my package to untar uncleanly, so I'm hoping you can help me out with this -- and if not, I'm hoping you can turn me in the right direction.

Thanks!

**Comment by doublep** [comment]
I don't know what leads to it, but the error is gone if I make the version in `org-gtd-pkg.el` consistent with what is declared in `org-gtd.el`, i.e. change 2.2.0 to 2.3.0. Maybe best to just delete explicit `-pkg.el` file?

Maybe leave this bug open, eventually Eldev should warn about such things.

Quick debug how-to:
* Grep Emacs sources for error message; this shows that the error comes from `package-untar-buffer` (actually, this could be found from backtrace too, didn't think about that).
* Find a command to reproduce this locally. I eventually settled on `eldev -dtp test`; the important option is `-p`.
* Create file `Eldev-local` in the project. In it, add form `(require 'package)` and then *replace* function `package-untar-buffer` (defined by requiring the feature) by copying it from Emacs source code. Now you have your own definition you can play with.
* Before `or` form in the function, I just inserted this: `(eldev-dump regexp name dir tar-data (string-match regexp name))`.
* I still couldn't make sense from the output, but I noticed that it mentioned two versions at once: 2.2.0 and 2.3.0.
* Now grep the package and find if it itself somehow declares two conflicting versions. Bingo!

**Comment by Trevoke** [comment]
Thanks! Fixed the problem, found a bug in the product logic, and fixed that. Much appreciated!
I'll store your quick debug how-to for later use!
